---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define apache_packages.
  set_fact:
    apache_packages: "{{ __apache_packages | list }}"
  when: apache_packages is not defined

- name: Define php_packages.
  set_fact:
    php_packages: "{{ __php_packages | list }}"
  when: php_packages is not defined

- name: Define mariadb_packages.
  set_fact:
    mariadb_packages: "{{ __mariadb_packages | list }}"
  when: mariadb_packages is not defined

- name: Define unzip_packages.
  set_fact:
    unzip_packages: "{{ __unzip_packages | list }}"
  when: unzip_packages is not defined
  
- name: Define apache_extra_packages.
  set_fact:
    apache_extra_packages: "{{ __apache_extra_packages | list }}"
  when: apache_extra_packages is not defined

# Setup/install tasks..
- include_tasks: "setup-{{ ansible_os_family }}.yml"